### ISSUE TITLE
Standalone version has insecure version of CAS module

### ISSUE THREAD

**Issue by pvandrunen** [bwood/ucberkeley_cas-7#51]
https://www.drupal.org/project/cas/releases/7.x-1.5
New release of CAS contains security fix.  

I tried updating just CAS within the Berkeley CAS module but there were errors locating the library.

**Comment by bwood** [comment]
That security release only applies to the cas_server sub module which is not enabled by this feature. The README here lists a mailing list for this project. In Feb I sent a PSA about this  to that list explaining that this feature would not be updated for this CAS release. Also see the FAQ about module updates in the README.
